USE oldschool_tools;
CREATE TABLE ITEMS(
  ITEMID          INT NOT NULL AUTO_INCREMENT,
  ITEMNAME          NVARCHAR(40) NOT NULL,
  ITEMDESCRIPTION   NVARCHAR(200) NULL,
  EXAMINETEXT       NVARCHAR(200) NULL,
  TRADEABLE         BOOLEAN NULL,
  PRIMARY KEY (ITEMID)
);