CREATE TABLE QUESTQUESTREQUIREMENTS(
  QUESTQUESTREQUIREMENTGUID   CHAR(38) NOT NULL,
  QUESTGUID                   CHAR(38) NOT NULL, -- The quest which requires the quest
  REQUIREDQUESTGUID             CHAR(38) NOT NULL, -- The quest that needs to be completed
  PRIMARY KEY (QUESTQUESTREQUIREMENTGUID),
  FOREIGN KEY (QUESTGUID) REFERENCES QUESTS(QUESTGUID),
  FOREIGN KEY (PARENTQUESTGUID) REFERENCES QUESTS(QUESTGUID)
);