USE oldschool_tools;
CREATE TABLE QUESTSKILLREWARDS(
  QUESTSKILLREWARDID    INT NOT NULL AUTO_INCREMENT,
  QUESTID               INT NOT NULL,
  SKILLID               INT NOT NULL,
  XPREWARD                INTEGER NULL,
  CONDITIONAL             BOOLEAN NULL,
  OPTIONAL                BOOLEAN NULL,
  COMMENT                 NVARCHAR(1000),
  PRIMARY KEY (QUESTSKILLREWARDID),
  FOREIGN KEY (QUESTID) REFERENCES QUESTS(QUESTID),
  FOREIGN KEY (SKILLID) REFERENCES SKILLS(SKILLID)
);