USE oldschool_tools;
CREATE TABLE QUESTITEMREQUIREMENTS(
  QUESTITEMREQUIREMENTID      INT NOT NULL AUTO_INCREMENT,
  QUESTID                     INT NOT NULL,
  ITEMID                      INT NOT NULL,
  AMOUNT                      INTEGER NULL,
  OPTIONAL                    BOOLEAN NULL,
  PRIMARY KEY (QUESTITEMREQUIREMENTID),
  FOREIGN KEY (QUESTID) REFERENCES QUESTS(QUESTID),
  FOREIGN KEY (ITEMID) REFERENCES ITEMS(ITEMID)
);