CREATE TABLE QUESTSKILLREWARDS(
  QUESTSKILLREWARDGUID    CHAR(38) NOT NULL,
  QUESTGUID               CHAR(38) NOT NULL,
  SKILLGUID               CHAR(38) NOT NULL,
  XPREWARD                INTEGER NULL,
  CONDITIONAL             BOOLEAN NULL,
  OPTIONAL                BOOLEAN NULL,
  COMMENT                 NVARCHAR(1000),
  PRIMARY KEY (QUESTSKILLREWARDGUID),
  FOREIGN KEY (QUESTGUID) REFERENCES QUESTS(QUESTGUID),
  FOREIGN KEY (SKILLGUID) REFERENCES SKILLS(SKILLGUID)
);