CREATE TABLE QUESTQUESTREQUIREMENTS(
  QUESTQUESTREQUIREMENTID   INT NOT NULL AUTO_INCREMENT,
  QUESTID                   INT NOT NULL, -- The quest which requires the quest
  REQUIREDQUESTID             INT NOT NULL, -- The quest that needs to be completed
  PRIMARY KEY (QUESTQUESTREQUIREMENTID),
  FOREIGN KEY (QUESTID) REFERENCES QUESTS(QUESTID),
  FOREIGN KEY (PARENTQUESTID) REFERENCES QUESTS(QUESTID)
);