USE oldschool_tools;
CREATE TABLE USERS(
  USERID                    INT NOT NULL AUTO_INCREMENT,
  USERROLEID                INT NOT NULL,
  EMAILADDRESS              NVARCHAR(100) NOT NULL,
  PASSWORD                  NVARCHAR(255) NOT NULL,
  COMMENT                   NVARCHAR(1000),
  PRIMARY KEY (USERID),
  FOREIGN KEY (USERROLEID) REFERENCES USERROLES(USERROLEID)
);