USE oldschool_tools;
INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('A Soul''s Bane',1,1,1,0,1,102);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('A Tail of Two Cats',2,2,1,1,2,87);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('A Taste of Hope',3,1,1,2,2,138);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Animal Magnetism',4,1,1,1,1,117);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Another Slice of H.A.M.',5,1,1,1,1,125);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Between a Rock...',6,2,1,2,2,74);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Big Chompy Bird Hunting',7,2,1,1,0,52);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Biohazard',8,3,1,0,1,38);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Black Knights'' Fortress',9,3,0,0,0,12);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Bone Voyage',10,1,1,1,0,132);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Cabin Fever',11,2,1,2,1,98);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Client of Kourend',12,1,1,0,1,131);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Clock Tower',13,1,1,0,0,29);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Cold War',14,1,1,1,1,119);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Contact!',15,1,1,3,1,118);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Cook''s Assistant',16,1,0,0,0,1);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Creature of Fenkenstrain',17,2,1,1,1,69);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Darkness of Hallowvale',18,2,1,1,3,111);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Death Plateau',19,1,1,0,1,56);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Death to the Dorgeshuun',20,1,1,1,1,107);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Demon Slayer',21,2,0,0,0,2);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Desert Treasure',22,3,1,3,2,77);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Devious Minds',23,1,1,2,0,95);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Doric''s Quest',24,3,0,0,1,11);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Dragon Slayer',25,1,0,0,0,17);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Dragon Slayer II',26,5,1,4,3,136);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Dream Mentor',27,2,1,3,0,126);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Druidic Ritual',28,4,1,0,0,18);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Dwarf Cannon',29,1,1,0,0,46);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Eadgar''s Ruse',30,1,1,2,1,60);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Eagles'' Peak',31,2,1,0,1,116);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Elemental Workshop I',32,1,1,0,0,53);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Elemental Workshop II',33,1,1,1,1,113);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Enakhra''s Lament',34,2,1,2,1,97);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Enlightened Journey',35,1,1,1,0,115);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Ernest the Chicken',36,2,0,2,2,7);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Fairytale I - Growing Pains',37,2,1,2,2,99);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Fairytale II - Cure a Queen',38,2,1,2,0,108);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Family Crest',39,1,1,2,1,24);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Fight Arena',40,2,1,2,0,32);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Fishing Contest',41,1,1,0,0,26);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Forgettable Tale...',42,2,1,1,2,85);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Garden of Tranquillity',43,2,1,1,3,86);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Gertrude''s Cat',44,1,1,0,0,49);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Ghosts Ahoy',45,2,1,1,2,71);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Goblin Diplomacy',46,4,0,0,0,15);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Grim Tales',47,1,1,3,1,127);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Haunted Mine',48,2,1,2,0,66);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Hazeel Cult',49,1,1,0,0,33);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Heroes'' Quest',50,1,1,2,1,22);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Holy Grail',51,2,1,1,1,30);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Horror from the Deep',52,2,1,2,0,63);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Icthlarin''s Little Helper',53,2,1,1,1,78);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Imp Catcher',54,5,0,0,0,9);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('In Aid of the Myreque',55,2,1,1,2,101);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('In Search of the Myreque',56,2,1,1,0,68);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Jungle Potion',57,1,1,0,0,39);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('King''s Ransom',58,1,1,2,1,128);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Legends'' Quest',59,4,1,3,3,50);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Lost City',60,3,1,2,0,19);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Lunar Diplomacy',61,2,1,2,2,109);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Making History',62,3,1,1,2,92);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Merlin''s Crystal',63,6,1,1,1,21);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Misthalin Mystery',64,1,0,0,0,130);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Monk''s Friend',65,1,1,0,0,27);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Monkey Madness I',66,3,1,3,2,65);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Monkey Madness II',67,4,1,4,3,129);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Mountain Daughter',68,2,1,1,1,73);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Mourning''s Ends Part I',69,2,1,3,2,84);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Mourning''s Ends Part II',70,2,1,3,3,89);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Murder Mystery',71,3,1,0,0,47);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('My Arm''s Big Adventure',72,1,1,1,1,114);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Nature Spirit',73,2,1,0,1,55);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Observatory Quest',74,2,1,0,0,43);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Olaf''s Quest',75,1,1,1,0,124);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('One Small Favour',76,2,1,2,3,72);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Pirate''s Treasure',77,1,0,1,1,16);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Plague City',78,1,1,0,0,35);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Priest in Peril',79,1,1,0,1,54);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Prince Ali Rescue',80,1,0,0,1,10);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Rag and Bone Man',81,1,1,0,1,103);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Rag and Bone Man II',82,1,1,1,2,104);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Ratcatchers',83,2,1,1,2,93);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Recipe for Disaster: Another Cook''s Quest',84,1,1,5,0,100);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Recipe for Disaster: Final Fight',85,1,1,5,3,100);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Recipe for Disaster: Freeing Evil Dave',86,1,1,5,1,100);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Recipe for Disaster: Freeing King Awowogei',87,1,1,5,1,100);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Recipe for Disaster: Freeing Pirate Pete',88,1,1,5,1,100);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Recipe for Disaster: Freeing Sir Amik Varze',89,1,1,5,1,100);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Recipe for Disaster: Freeing Skrach Uglogwee',90,1,1,5,1,100);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Recipe for Disaster: Freeing the Goblin generals',91,1,1,5,0,100);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Recipe for Disaster: Freeing the Lumbridge Guide',92,1,1,5,0,100);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Recipe for Disaster: Freeing the Mountain dwarf',93,1,1,5,0,100);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Recruitment Drive',94,1,1,0,0,83);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Regicide',95,3,1,3,2,59);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Romeo & Juliet',96,2,0,0,0,4);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Roving Elves',97,1,1,3,0,70);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Royal Trouble',98,1,1,2,1,106);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Rum Deal',99,2,1,2,1,90);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Rune Mysteries',100,3,0,0,0,51);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Scorpion Catcher',101,1,1,1,1,23);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Sea Slug',102,1,1,1,0,36);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Shades of Mort''ton',103,3,1,1,0,61);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Shadow of the Storm',104,1,1,1,1,91);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Sheep Herder',105,4,1,0,0,34);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Sheep Shearer',106,1,0,0,0,5);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Shield of Arrav',107,5,0,0,0,6);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Shilo Village',108,2,1,2,2,41);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Spirits of the Elid',109,2,1,1,0,94);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Swan Song',110,2,1,3,1,105);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Tai Bwo Wannai Trio',111,2,1,1,2,58);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Tale of the Righteous',112,1,1,0,1,137);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Tears of Guthix',113,1,1,1,0,79);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Temple of Ikov',114,1,1,2,1,28);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Corsair Curse',115,1,0,0,0,135);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Depths of Despair',116,1,1,0,0,134);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Digsite',117,2,1,1,1,48);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Eyes of Glouphrie',118,2,1,1,1,110);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Feud',119,1,1,1,1,75);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Fremennik Isles',120,1,1,2,2,120);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Fremennik Trials',121,3,1,1,2,62);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Giant Dwarf',122,2,1,1,2,82);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Golem',123,1,1,1,1,76);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Grand Tree',124,5,1,2,2,40);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Great Brain Robbery',125,2,1,2,1,122);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Hand in the Sand',126,1,1,1,1,96);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Knight''s Sword',127,1,0,0,0,14);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Lost Tribe',128,1,1,1,1,81);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Queen of Thieves',129,1,1,0,0,133);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Restless Ghost',130,1,0,0,1,3);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Slug Menace',131,1,1,1,1,112);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('The Tourist Trap',132,2,1,1,1,44);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Throne of Miscellania',133,1,1,2,1,64);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Tower of Life',134,2,1,0,1,121);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Tree Gnome Village',135,2,1,1,0,31);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Tribal Totem',136,1,1,1,0,25);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Troll Romance',137,2,1,2,1,67);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Troll Stronghold',138,1,1,2,0,57);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Underground Pass',139,5,1,2,2,42);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Vampire Slayer',140,3,0,0,0,8);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Wanted!',141,1,1,1,2,88);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Watchtower',142,4,1,1,2,45);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Waterfall Quest',143,1,1,1,1,37);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('What Lies Below',144,1,1,1,1,123);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Witch''s House',145,4,1,1,0,20);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Witch''s Potion',146,1,0,0,0,13);

INSERT QUESTS (QUESTNAME,QUESTID,QUESTPOINTS,MEMBERS,DIFFICULTY,LENGTH,QUESTNUMBER)
VALUES ('Zogre Flesh Eaters',147,1,1,1,1,80);

