INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (1,4,13,19,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (2,4,5,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (3,4,19,18,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (4,4,9,35,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (5,5,1,15,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (6,5,6,25,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (7,6,3,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (8,6,15,40,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (9,6,14,50,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (10,7,8,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (11,7,10,5,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (12,7,5,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (13,11,17,42,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (14,11,13,45,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (15,11,5,40,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (16,11,14,50,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (17,14,17,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (18,14,13,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (19,14,22,10,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (20,14,23,34,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (21,17,13,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (22,17,18,25,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (23,18,17,26,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (24,18,23,5,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (25,18,13,32,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (26,18,7,33,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (27,18,15,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (28,18,2,40,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (29,18,18,22,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (30,20,18,23,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (31,20,17,23,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (32,22,12,50,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (33,22,7,50,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (34,22,19,10,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (35,22,18,53,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (36,23,10,50,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (37,23,21,50,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (38,23,14,65,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (39,26,17,60,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (40,26,23,50,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (41,26,13,62,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (42,26,7,75,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (43,26,15,68,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (44,26,14,70,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (45,26,18,60,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (46,27,24,85,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (47,30,16,31,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (48,31,22,27,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (49,32,13,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (50,32,15,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (51,32,14,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (52,33,7,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (53,33,14,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (54,34,13,50,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (55,34,12,45,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (56,34,7,39,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (57,34,6,43,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (58,35,13,36,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (59,35,20,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (60,35,12,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (61,38,18,40,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (62,38,20,49,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (63,38,16,57,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (64,39,13,40,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (65,39,15,40,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (66,39,14,40,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (67,39,7,59,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (68,41,11,10,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (69,42,8,22,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (70,42,20,17,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (71,121,9,56,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (72,43,20,25,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (73,45,17,25,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (74,45,8,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (75,47,17,59,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (76,47,20,45,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (77,47,16,52,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (78,47,18,58,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (79,47,9,71,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (80,48,17,15,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (81,48,13,35,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (82,50,8,53,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (83,50,11,53,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (84,50,16,25,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (85,50,15,50,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (86,51,1,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (87,52,17,35,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (88,55,13,25,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (89,55,7,7,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (90,55,15,15,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (91,56,17,25,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (92,57,16,3,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (93,58,3,65,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (94,58,7,45,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (95,59,13,50,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (96,59,16,45,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (97,59,7,56,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (98,59,15,52,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (99,59,6,42,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (100,59,14,50,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (101,59,2,50,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (102,59,18,50,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (103,59,9,50,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (104,59,17,50,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (105,60,9,36,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (106,60,13,31,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (107,61,13,61,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (108,61,3,40,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (109,61,12,49,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (110,61,16,5,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (111,61,7,65,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (112,61,15,60,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (113,61,9,55,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (114,67,17,55,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (115,67,13,70,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (116,67,22,60,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (117,67,19,69,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (118,67,18,55,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (119,67,12,60,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (120,68,17,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (121,69,5,60,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (122,69,18,50,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (123,72,20,29,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (124,72,9,10,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (125,74,13,10,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (126,75,12,40,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (127,75,9,50,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (128,76,13,25,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (129,76,16,18,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (130,76,14,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (131,76,17,36,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (132,82,3,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (133,82,19,40,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (134,87,17,48,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (135,84,8,10,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (136,86,8,25,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (137,88,8,31,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (138,92,8,40,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (139,90,8,41,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (140,87,8,70,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (141,90,12,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (142,95,17,56,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (143,98,19,40,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (144,98,17,40,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (145,99,13,42,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (146,99,19,42,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (147,99,20,40,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (148,99,11,50,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (149,99,6,47,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (150,101,6,31,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (151,102,12,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (152,103,13,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (153,103,16,15,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (154,104,13,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (155,108,13,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (156,108,17,32,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (157,131,13,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (158,131,21,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (159,131,19,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (160,109,15,37,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (161,109,7,33,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (162,109,5,37,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (163,109,18,37,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (164,110,8,62,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (165,110,13,40,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (166,110,12,42,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (167,110,14,45,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (168,110,11,62,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (169,110,7,66,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (170,111,17,15,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (171,111,8,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (172,111,11,5,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (173,113,13,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (174,113,12,49,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (175,113,15,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (176,114,5,40,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (177,114,18,42,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (178,117,17,10,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (179,117,16,10,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (180,117,18,25,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (181,118,23,5,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (182,118,7,46,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (183,118,21,13,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (184,119,18,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (185,120,23,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (186,120,13,46,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (187,120,17,40,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (188,121,9,40,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (189,121,13,40,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (190,121,10,25,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (191,122,13,12,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (192,122,12,16,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (193,122,7,33,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (194,122,18,14,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (195,123,13,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (196,123,18,25,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (197,124,17,25,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (198,125,23,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (199,125,13,16,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (200,125,6,50,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (201,126,13,49,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (202,126,18,17,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (203,127,15,10,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (204,128,17,13,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (205,128,15,17,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (206,128,18,13,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (207,131,18,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (208,132,10,10,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (209,132,14,20,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (210,134,23,10,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (211,136,18,21,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (212,137,17,28,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (213,138,17,15,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (214,139,5,25,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (215,142,17,25,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (216,142,16,14,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (217,142,7,15,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (218,142,18,15,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (219,142,15,40,1);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (220,144,21,35,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (221,147,10,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (222,147,16,8,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (223,147,5,30,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (224,147,14,4,0);

INSERT QUESTSKILLREQUIREMENTS (QUESTSKILLREQUIREMENTID,QUESTID,SKILLID,LEVEL,BOOSTABLE)
VALUES (225,147,2,20,0);

