USE oldschool_tools;
INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (2,53);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (4,130);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (4,36);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (4,79);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (5,20);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (5,117);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (5,122);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (6,41);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (6,29);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (8,78);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (11,99);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (11,77);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (15,44);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (15,53);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (15,80);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (17,79);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (17,130);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (18,55);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (20,128);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (22,117);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (22,132);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (22,114);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (22,79);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (22,143);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (22,138);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (23,24);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (23,138);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (23,141);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (23,94);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (27,61);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (27,30);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (30,28);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (33,32);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (37,60);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (37,73);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (38,37);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (42,122);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (42,41);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (43,17);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (45,79);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (45,130);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (47,145);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (48,79);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (50,107);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (50,60);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (50,63);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (50,25);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (53,44);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (55,56);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (55,73);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (56,73);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (58,63);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (58,51);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (58,71);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (58,9);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (58,76);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (59,50);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (59,39);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (59,108);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (59,139);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (59,143);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (61,60);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (61,121);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (61,108);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (62,79);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (62,130);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (66,124);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (66,135);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (67,35);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (67,118);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (67,87);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (67,138);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (67,142);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (67,66);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (69,97);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (69,7);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (69,105);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (70,69);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (72,30);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (72,119);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (72,57);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (73,79);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (73,130);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (75,121);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (76,100);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (76,108);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (76,28);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (83,53);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (84,16);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (93,84);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (93,41);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (91,84);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (91,46);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (88,84);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (92,84);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (92,7);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (92,8);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (92,21);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (92,71);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (92,73);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (92,145);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (86,84);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (86,44);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (86,104);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (90,84);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (90,7);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (89,84);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (89,39);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (89,50);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (89,108);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (89,139);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (89,143);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (87,84);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (87,66);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (85,84);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (85,93);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (85,91);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (85,88);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (85,92);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (85,86);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (85,90);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (85,89);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (85,87);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (85,22);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (85,52);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (94,9);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (94,28);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (95,139);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (97,95);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (97,143);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (98,133);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (99,147);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (104,123);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (104,21);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (108,57);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (110,76);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (110,43);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (111,57);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (118,124);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (120,121);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (125,17);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (125,88);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (125,99);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (125,11);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (128,46);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (128,100);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (131,102);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (131,141);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (133,50);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (133,121);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (137,138);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (137,19);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (138,19);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (139,8);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (141,94);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (141,128);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (141,100);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (141,79);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (142,28);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (144,100);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (147,57);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (147,7);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (10,117);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (129,12);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (116,12);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (26,12);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (26,59);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (26,27);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (26,2);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (26,4);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (26,45);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (26,10);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (112,12);

INSERT QUESTQUESTREQUIREMENTS (QUESTID,REQUIREDQUESTID)
VALUES (3,18);

