INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Attack',1);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Defence',3);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Strength',2);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Hitpoints',4);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Ranged',5);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Prayer',6);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Magic',7);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Cooking',8);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Woodcutting',9);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Fletching',10);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Fishing',11);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Firemaking',12);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Crafting',13);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Smithing',14);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Mining',15);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Herblore',16);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Agility',17);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Thieving',18);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Slayer',19);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Farming',20);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Runecrafting',21);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Hunter',22);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Construction',23);

INSERT SKILLS (SKILLNAME,SKILLID)
VALUES ('Combat',24);

