INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (0, 'Attack');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (1, 'Strength');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (2, 'Defence');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (3, 'HitPoints');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (4, 'Ranged');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (5, 'Prayer');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (6, 'Magic');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (7, 'Cooking');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (8, 'Woodcutting');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (9, 'Fletching');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (10, 'Fishing');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (11, 'Firemaking');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (12, 'Crafting');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (13, 'Smithing');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (14, 'Mining');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (15, 'Herblore');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (16, 'Agility');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (17, 'Thieving');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (18, 'Slayer');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (19, 'Farming');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (20, 'Runecrafting');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (21, 'Hunter');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (22, 'Construction');

INSERT INTO SKILLS (SKILLID, SKILLNAME)
 VALUES (23, 'Combat');