USE oldschool_tools;
INSERT USERROLES (USERROLEID,ROLENAME,ROLECODE)
VALUES (1,'Admin','ADM');

INSERT USERROLES (USERROLEID,ROLENAME,ROLECODE)
VALUES (2,'Moderator','MOD');

INSERT USERROLES (USERROLEID,ROLENAME,ROLECODE)
VALUES (3,'Standard','STD');x