CREATE TABLE QUESTSKILLREQUIREMENTS(
  QUESTSKILLREQUIREMENTGUID     CHAR(38) NOT NULL,
  QUESTGUID                     CHAR(38) NOT NULL,
  SKILLGUID                     CHAR(38) NOT NULL,
  LEVEL                         INTEGER NOT NULL,
  OPTIONAL                      BOOLEAN NULL,
  COMMENT                       NVARCHAR(1000) NULL,
  PRIMARY KEY (QUESTSKILLREQUIREMENTGUID),
  FOREIGN KEY (QUESTGUID) REFERENCES QUESTS(QUESTGUID),
  FOREIGN KEY (SKILLGUID) REFERENCES SKILLS(SKILLGUID)
);